spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: AWS RDS
    username: AWS RDS
    password: AWS RDS

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    mail:
      host: smtp.gmail.com
      port: 587
      username: email
      password: key
      properties:
        mail:
          smtp:
            starttls:
              enable: true
